services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: linguai_backend
      POSTGRES_PASSWORD: "BaJy52uJVsjeDsI2CGSckt61L1kdHxw7"
    volumes:
      - linguai_backend_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "Sy2goSJOxLJIXnjtxCgMHpuwe-CSX5Xp"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: linguai_backend_test
      POSTGRES_PASSWORD: "ERZNs-_TaHp9pW6SJSmf7s3jt85Gf4QA"
    volumes:
      - linguai_backend_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "tTYDOcHibEYZlE0NQd60od9N-zL68e7b"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  linguai_backend_data:
  linguai_backend_test_data:
